# Generated by Django 3.2.2 on 2022-03-21 11:30

import bakerycustomersinvoices.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_type', models.CharField(choices=[('Company', 'Company'), ('Enterprise', 'Enterprise'), ('Individual', 'Individual'), ('School', 'School'), ('NGOs', 'NGOs')], max_length=10)),
                ('company_name', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('address', models.TextField(max_length=255, null=True, verbose_name='Address')),
                ('city', models.CharField(default='Kumba', max_length=100, verbose_name='City')),
                ('region', models.CharField(default='South West Region', max_length=200, verbose_name='Region')),
                ('phone', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +237', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('sales_session', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='Morning', max_length=500, null=True, verbose_name='Session')),
                ('stock_manager', models.CharField(blank=True, max_length=500, null=True, verbose_name='Procurement Manager')),
                ('invoice_id', models.CharField(blank=True, default=bakerycustomersinvoices.models.increment_invoice_number, max_length=500, null=True)),
                ('stock_dept_invoice_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stock Dept Invoice Id')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakerycustomersinvoices.customer', verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('invoice_id', models.CharField(default='', max_length=100)),
                ('stock_manager', models.CharField(blank=True, max_length=500, null=True, verbose_name='Procurement Manager')),
                ('category', models.CharField(default='', max_length=100)),
                ('product', models.CharField(default='', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('payment_session', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='Morning', max_length=500, null=True)),
                ('payment_installment', models.CharField(blank=True, choices=[('1st Installment', '1st Installment'), ('2nd Installment', '2nd Installment'), ('3rd Installment', '3rd Installment'), ('4th Installment', '4th Installment'), ('5th Installment', '5th Installment'), ('6th Installment', '6th Installment'), ('7th Installment', '7th Installment'), ('8th Installment', '8th Installment'), ('9th Installment', '9th Installment'), ('10th Installment', '10th Installment')], default='1st Installment', max_length=500, null=True)),
                ('payment_id', models.CharField(blank=True, default=bakerycustomersinvoices.models.increment_invoice_number, max_length=500, null=True)),
                ('employee', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakerycustomersinvoices.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakerycustomersinvoices.customer')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
