# Generated by Django 4.0.4 on 2022-05-31 10:20

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid4, max_length=100, null=True, unique=True)),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Boulangerie', 'Boulangerie'), ('Ice Cream', 'Ice Cream')], default='', max_length=500, null=True, verbose_name='Department')),
                ('employee_management', models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Management', 'Management')], default='', max_length=500, null=True, verbose_name='Employee / Management')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Employee')),
                ('transaction_id', models.CharField(max_length=200, verbose_name='Transaction Id')),
                ('reference_id', models.CharField(max_length=200, verbose_name='Reference Id')),
                ('institution', models.CharField(max_length=200, verbose_name='Institution')),
                ('description', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Description')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('accounts_dr', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Account Debit')),
                ('accounts_cr', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='AccountsCredit')),
            ],
            options={
                'verbose_name': 'Accounts Payable',
                'verbose_name_plural': 'Accounts Payable',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid4, max_length=100, null=True, unique=True)),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Boulangerie', 'Boulangerie'), ('Ice Cream', 'Ice Cream')], default='', max_length=500, null=True, verbose_name='Department')),
                ('employee_management', models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Management', 'Management')], default='', max_length=500, null=True, verbose_name='Employee / Management')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Employee')),
                ('transaction_id', models.CharField(max_length=200, verbose_name='Transaction Id')),
                ('bank_name', models.CharField(default='', max_length=200, verbose_name='Bank Name')),
                ('description', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Description')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('accounts_dr', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Account Debit')),
                ('accounts_cr', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='AccountsCredit')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Bank',
            },
        ),
        migrations.CreateModel(
            name='Creditors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid4, max_length=100, null=True, unique=True)),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Boulangerie', 'Boulangerie'), ('Ice Cream', 'Ice Cream')], default='', max_length=500, null=True, verbose_name='Department')),
                ('employee_management', models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Management', 'Management')], default='', max_length=500, null=True, verbose_name='Employee / Management')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Employee')),
                ('transaction_id', models.CharField(max_length=200, verbose_name='Transaction Id')),
                ('invoice_id', models.CharField(max_length=200, verbose_name='Invoice Id')),
                ('vendor', models.CharField(max_length=200, verbose_name='vendor')),
                ('description', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Description')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('accounts_dr', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Account Debit')),
                ('accounts_cr', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='AccountsCredit')),
            ],
            options={
                'verbose_name': 'Creditor',
                'verbose_name_plural': 'Creditors',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid4, max_length=100, null=True, unique=True)),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Boulangerie', 'Boulangerie'), ('Ice Cream', 'Ice Cream')], default='', max_length=500, null=True, verbose_name='Department')),
                ('employee_management', models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Management', 'Management')], default='', max_length=500, null=True, verbose_name='Employee / Management')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Employee')),
                ('transaction_id', models.CharField(max_length=200, verbose_name='Transaction Id')),
                ('institution', models.CharField(max_length=200, verbose_name='Institution')),
                ('description', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Description')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('accounts_dr', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Account Debit')),
                ('accounts_cr', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='AccountsCredit')),
            ],
            options={
                'verbose_name': 'Expenses',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid4, max_length=100, null=True, unique=True)),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Boulangerie', 'Boulangerie'), ('Ice Cream', 'Ice Cream')], default='', max_length=500, null=True, verbose_name='Department')),
                ('employee_management', models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Management', 'Management')], default='', max_length=500, null=True, verbose_name='Employee / Management')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Employee')),
                ('invoice_id', models.CharField(max_length=200, verbose_name='Invoice Id')),
                ('vendor', models.CharField(max_length=200, verbose_name='vendor')),
                ('description', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Description')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('accounts_dr', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Account Debit')),
                ('accounts_cr', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='AccountsCredit')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
    ]
