# Generated by Django 3.2.2 on 2022-04-01 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryRmReturns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('return_manager', models.CharField(max_length=200, verbose_name='Procuement Manager')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('return_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Purchase Invoice Id')),
                ('supplier', models.CharField(max_length=200, verbose_name='Supplier')),
                ('category', models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect')], default='Direct', max_length=500, null=True, verbose_name='Category')),
                ('entry_measure', models.CharField(max_length=200, verbose_name='Entry Measure')),
                ('weight_pack', models.CharField(max_length=200, verbose_name='Weight/Pack')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BakeryRmReturn',
                'verbose_name_plural': 'BakeryRmReturns',
            },
        ),
    ]
