# Generated by Django 3.2.2 on 2022-04-04 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeryrmreturns',
            name='employee',
        ),
    ]
