# Generated by Django 3.2.2 on 2022-04-05 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0002_remove_bakeryrmreturns_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='general_accounting_ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Boulangerie', 'Boulangerie'), ('Ice Cream', 'Ice Cream')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('employee_management', models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Management', 'Management')], default='Employee', max_length=500, null=True, verbose_name='Employee / Manager')),
                ('transaction_Id', models.CharField(max_length=200, verbose_name='Transaction Id')),
                ('reference_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reference Id')),
                ('institution', models.CharField(max_length=200, verbose_name='Institution')),
                ('description', models.TextField(blank=True, max_length=2500, null=True, verbose_name='Description')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('accounts_dr', models.FloatField(default=0.0, verbose_name='Account Debit')),
                ('accounts_cr', models.FloatField(default=0.0, verbose_name='AccountsCredit')),
            ],
            options={
                'verbose_name': 'General Ledger',
                'verbose_name_plural': 'General Ledger',
            },
        ),
        migrations.DeleteModel(
            name='BakeryRmReturns',
        ),
    ]
