# Generated by Django 3.2.2 on 2022-04-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0003_auto_20220405_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_accounting_ledger',
            name='accounts_cr',
            field=models.CharField(max_length=200, verbose_name='AccountsCredit'),
        ),
        migrations.AlterField(
            model_name='general_accounting_ledger',
            name='accounts_dr',
            field=models.CharField(max_length=200, verbose_name='Account Debit'),
        ),
    ]
