# Generated by Django 3.2.2 on 2022-04-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0005_rename_general_accounting_ledger_generalledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledger',
            name='category',
            field=models.CharField(blank=True, choices=[('Assets', 'Assets'), ('Liabilities', 'Liabilities'), ('Equity', 'Equity'), ('Revenues', 'Revenues'), ('Expenses', 'Expenses')], max_length=500, null=True, verbose_name='Category'),
        ),
    ]
