# Generated by Django 3.2.2 on 2022-04-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0006_generalledger_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='department',
            field=models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Boulangerie', 'Boulangerie'), ('Ice Cream', 'Ice Cream')], default='', max_length=500, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='employee_management',
            field=models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Management', 'Management')], default='', max_length=500, null=True, verbose_name='Employee / Management'),
        ),
    ]
