# Generated by Django 3.2.2 on 2022-04-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0007_auto_20220406_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledger',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('Fixed Assets', 'Fixed Assets'), ('Current Assets', 'Current Assets'), ('Current Liabilities', 'Current Liabilities'), ('Non Current Liabilities', 'Non Current Liabilities'), ('Equity', 'Equity'), ('Revenues', 'Revenues'), ('Expenses', 'Expenses'), ('Accrued expenses', 'Accrued expenses')], max_length=500, null=True, verbose_name='Sub Category'),
        ),
    ]
