# Generated by Django 3.2.2 on 2022-04-07 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0008_generalledger_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalledger',
            old_name='transaction_Id',
            new_name='transaction_id',
        ),
    ]
