# Generated by Django 3.2.2 on 2022-04-07 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0009_rename_transaction_id_generalledger_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalledger',
            name='category',
        ),
        migrations.RemoveField(
            model_name='generalledger',
            name='sub_category',
        ),
    ]
