# Generated by Django 3.2.2 on 2022-04-07 02:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0010_auto_20220407_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledger',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, max_length=100, null=True, unique=True),
        ),
    ]
