# Generated by Django 4.0.4 on 2022-04-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0012_expenses_delete_generalledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='accounts_cr',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='AccountsCredit'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='accounts_dr',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Account Debit'),
        ),
    ]
