# Generated by Django 4.0.4 on 2022-04-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0015_bank_creditors_purchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='vendor',
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(default='', max_length=200, verbose_name='Bank Name'),
        ),
    ]
