# Generated by Django 4.0.4 on 2022-05-31 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoulangerieInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('session', models.CharField(blank=True, choices=[('1st Session', '1st Session'), ('2nd Session', '2nd Session')], default='', max_length=500, null=True, verbose_name='Session')),
                ('department', models.CharField(blank=True, choices=[('Boulangerie', 'Boulangerie')], default='Boualangerie', max_length=500, null=True, verbose_name='Department')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Employee')),
                ('stock_status', models.CharField(blank=True, choices=[('Opening Stock', 'Opening Stock'), ('Closing Stock', 'Closing Stock')], default='', max_length=500, null=True, verbose_name='Stock Status')),
                ('sub_department', models.CharField(blank=True, choices=[('Boulangerie', 'Boulangerie'), ('Patisserie', 'Patisserie')], default='', max_length=500, null=True, verbose_name='Sub Department')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('unit_selling_price', models.FloatField(default=0.0, verbose_name='Unit Selling Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
                ('total_selling_price', models.FloatField(default=0.0, verbose_name='Total Selling Price')),
                ('gross_profit', models.FloatField(default=0.0, verbose_name='Gross Profit')),
                ('margin', models.FloatField(default=0.0, verbose_name='margin')),
            ],
            options={
                'verbose_name': 'Boulangerie Inventory',
                'verbose_name_plural': 'Boulangerie Inventory',
            },
        ),
        migrations.CreateModel(
            name='BoulangerieLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('session', models.CharField(blank=True, choices=[('1st Session', '1st Session'), ('2nd Session', '2nd Session')], default='', max_length=500, null=True, verbose_name='Session')),
                ('department', models.CharField(blank=True, choices=[('Boulangerie', 'Boulangerie')], default='Boualangerie', max_length=500, null=True, verbose_name='Department')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Employee')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('accounts_dr', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Account Debit')),
                ('accounts_cr', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='AccountsCredit')),
            ],
            options={
                'verbose_name': 'Boulangerie Ledger',
                'verbose_name_plural': 'Boulangerie Ledger',
            },
        ),
        migrations.CreateModel(
            name='BoulangerieProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('category', models.CharField(max_length=200, verbose_name='Category')),
                ('sub_department', models.CharField(blank=True, choices=[('Boulangerie', 'Boulangerie'), ('Patisserie', 'Patisserie')], default='', max_length=500, null=True, verbose_name='Sub Department')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='BoulangeriePurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('session', models.CharField(blank=True, choices=[('1st Session', '1st Session'), ('2nd Session', '2nd Session')], default='', max_length=500, null=True, verbose_name='Session')),
                ('department', models.CharField(blank=True, choices=[('Boulangerie', 'Boulangerie')], default='Boualangerie', max_length=500, null=True, verbose_name='Department')),
                ('sub_department', models.CharField(blank=True, choices=[('Boulangerie', 'Boulangerie'), ('Patisserie', 'Patisserie')], default='', max_length=500, null=True, verbose_name='Sub Department')),
                ('stock_status', models.CharField(blank=True, choices=[('Purchases', 'Purchases')], default='', max_length=500, null=True, verbose_name='Stock Status')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Employee')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('unit_selling_price', models.FloatField(default=0.0, verbose_name='Unit Selling Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
                ('total_selling_price', models.FloatField(default=0.0, verbose_name='Total Selling Price')),
                ('gross_profit', models.FloatField(default=0.0, verbose_name='Gross Profit')),
                ('margin', models.FloatField(default=0.0, verbose_name='margin')),
            ],
            options={
                'verbose_name': 'Boulangerie Purchases',
                'verbose_name_plural': 'Boulangerie Purchases',
            },
        ),
        migrations.CreateModel(
            name='BoulangerieReturnsDamages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('session', models.CharField(blank=True, choices=[('1st Session', '1st Session'), ('2nd Session', '2nd Session')], default='', max_length=500, null=True, verbose_name='Session')),
                ('department', models.CharField(blank=True, choices=[('Boulangerie', 'Boulangerie'), ('Patisserie', 'Patisserie')], default='Boualangerie', max_length=500, null=True, verbose_name='Department')),
                ('employee', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Employee')),
                ('stock_status', models.CharField(blank=True, choices=[('Returns', 'Returns'), ('Damages', 'Damages')], default='', max_length=500, null=True, verbose_name='Stock Status')),
                ('sub_department', models.CharField(blank=True, choices=[('Boulangerie', 'Boulangerie'), ('Patisserie', 'Patisserie')], default='', max_length=500, null=True, verbose_name='Sub Department')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('unit_selling_price', models.FloatField(default=0.0, verbose_name='Unit Selling Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
                ('total_selling_price', models.FloatField(default=0.0, verbose_name='Total Selling Price')),
                ('gross_profit', models.FloatField(default=0.0, verbose_name='Gross Profit')),
                ('margin', models.FloatField(default=0.0, verbose_name='margin')),
            ],
            options={
                'verbose_name': 'Boulangerie-Returns-Damages',
                'verbose_name_plural': 'Boulangerie-Returns-Damages',
            },
        ),
        migrations.CreateModel(
            name='BoulangerieSubDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_department', models.CharField(blank=True, choices=[('Boulangerie', 'Boulangerie'), ('Patisserie', 'Patisserie')], default='', max_length=500, null=True, verbose_name='Sub Department')),
            ],
            options={
                'verbose_name': 'Sub Department',
                'verbose_name_plural': 'Sub Departments',
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, choices=[('1st Session', '1st Session'), ('2nd Session', '2nd Session')], default='', max_length=500, null=True, verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
    ]
