# Generated by Django 4.0.4 on 2022-04-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulangerie', '0003_alter_boulangerieledger_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boulangerieinventory',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('Opening Stock', 'Opening Stock'), ('Closing Stock', 'Closing Stock')], default='', max_length=500, null=True, verbose_name='Stock Status'),
        ),
        migrations.AlterField(
            model_name='boulangeriepurchases',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('Purchases', 'Purchases')], default='', max_length=500, null=True, verbose_name='Stock Status'),
        ),
        migrations.AlterField(
            model_name='boulangeriereturnsdamages',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('Returns', 'Returns'), ('Damages', 'Damages')], default='', max_length=500, null=True, verbose_name='Stock Status'),
        ),
    ]
