# Generated by Django 4.0.4 on 2022-04-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulangerie', '0004_alter_boulangerieinventory_stock_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boulangeriepurchases',
            name='department',
            field=models.CharField(blank=True, choices=[('Boulangerie', 'Boulangerie')], default='Boualangerie', max_length=500, null=True, verbose_name='Department'),
        ),
    ]
