# Generated by Django 4.0.4 on 2022-05-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulangerie', '0005_alter_boulangeriepurchases_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoulangerieProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('category', models.CharField(max_length=200, verbose_name='Category')),
                ('sub_department', models.CharField(blank=True, choices=[('Boulangerie', 'Boulangerie'), ('Patisserie', 'Patisserie')], default='', max_length=500, null=True, verbose_name='Sub Department')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, choices=[('1st Session', '1st Session'), ('2nd Session', '2nd Session')], default='', max_length=500, null=True, verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
    ]
