# Generated by Django 4.0.4 on 2022-05-31 10:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import purchase.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_type', models.CharField(choices=[('Company', 'Company'), ('Enterprise', 'Enterprise'), ('Individual', 'Individual')], max_length=10)),
                ('company_name', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('residential_address', models.TextField(max_length=255, null=True)),
                ('residential_city', models.CharField(default='Kumba', max_length=100)),
                ('residential_region', models.CharField(default='South West Region', max_length=200)),
                ('phone', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +237', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bank_name1', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_account_name1', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_account_number1', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('bank_name2', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_account_name2', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_account_number2', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Boulangerie', 'Boulangerie'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Ice Cream', 'Ice Cream')], default='', max_length=500, null=True, verbose_name='Department')),
                ('procurement_manager', models.CharField(blank=True, max_length=500, null=True, verbose_name='Procurement Manager')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('invoice_id', models.CharField(blank=True, default=purchase.models.increment_invoice_number, max_length=500, null=True)),
                ('stock_dept_invoice_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stock Dept Invoice Id')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('installment', models.CharField(blank=True, choices=[('1st Installment', '1st Installment'), ('2nd Installment', '2nd Installment'), ('3rd Installment', '3rd Installment'), ('4th Installment', '4th Installment'), ('5th Installment', '5th Installment'), ('6th Installment', '6th Installment'), ('7th Installment', '7th Installment'), ('8th Installment', '8th Installment'), ('9th Installment', '9th Installment'), ('10th Installment', '10th Installment'), ('11th Installment', '11th Installment'), ('12th Installment', '12th Installment'), ('13th Installment', '13th Installment'), ('14th Installment', '14th Installment'), ('15th Installment', '15th Installment'), ('16th Installment', '16th Installment'), ('17th Installment', '17th Installment')], default='1st Installment', max_length=20, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice_amount', models.IntegerField(default=0)),
                ('payment_id', models.CharField(blank=True, default=purchase.models.increment_payment_number, max_length=500, null=True)),
                ('amount_paid', models.IntegerField(default=0)),
                ('balance_due', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Boulangerie', 'Boulangerie'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Ice Cream', 'Ice Cream')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('product', models.CharField(blank=True, max_length=500, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('final_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='purchase.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(default=0)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.vendor')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
