# Generated by Django 4.0.4 on 2022-05-31 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupermarketInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, default='Supermarket', max_length=500, null=True, verbose_name='Department')),
                ('stock_manager', models.CharField(max_length=200, verbose_name='Stock Manager')),
                ('status', models.CharField(blank=True, choices=[('Opening Stock', 'Opening Stock'), ('Closing Stock', 'Closing Stock')], default='', max_length=500, null=True, verbose_name='status')),
                ('category', models.CharField(blank=True, max_length=200, null=True, verbose_name='Category')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('unit_selling_price', models.FloatField(default=0.0, verbose_name='Unit Selling Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
                ('total_selling_price', models.FloatField(default=0.0, verbose_name='Total Selling Price')),
                ('gross_profit', models.FloatField(default=0.0, verbose_name='Gross Profit')),
                ('margin', models.FloatField(default=0.0, verbose_name='margin')),
            ],
            options={
                'verbose_name': 'Supermarket Inventory',
                'verbose_name_plural': 'Supermarket Inventory',
            },
        ),
        migrations.CreateModel(
            name='SupermarketProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200, null=True, verbose_name='Category')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('unit_selling_price', models.FloatField(default=0.0, verbose_name='Unit Selling Price')),
            ],
            options={
                'verbose_name': 'Supermarket Products',
                'verbose_name_plural': 'Supermarket Products',
            },
        ),
        migrations.CreateModel(
            name='SupermarketPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, default='Supermarket', max_length=500, null=True, verbose_name='Department')),
                ('invoice_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Invoice Id')),
                ('category', models.CharField(blank=True, max_length=200, null=True, verbose_name='Category')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('unit_selling_price', models.FloatField(default=0.0, verbose_name='Unit Selling Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
                ('total_selling_price', models.FloatField(default=0.0, verbose_name='Total Selling Price')),
                ('gross_profit', models.FloatField(default=0.0, verbose_name='Gross Profit')),
                ('margin', models.FloatField(default=0.0, verbose_name='margin')),
            ],
            options={
                'verbose_name': 'Supermarket Purchases',
                'verbose_name_plural': 'Supermarket Purchases',
            },
        ),
        migrations.CreateModel(
            name='SupermarketReturnsDamages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, default='Supermarket', max_length=500, null=True, verbose_name='Department')),
                ('session', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=500, null=True, verbose_name='Session')),
                ('sales_person', models.CharField(max_length=200, verbose_name='Sales Person')),
                ('status', models.CharField(blank=True, choices=[('Return Inwards', 'Return Inwards'), ('Return Outwards', 'Return Outwards'), ('Damages', 'Damages'), ('Expired', 'Expired')], default='', max_length=200, null=True, verbose_name='Sales Person')),
                ('category', models.CharField(blank=True, max_length=200, null=True, verbose_name='Category')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
            ],
            options={
                'verbose_name': 'Supermarket-Returns-Damages-Expiry',
                'verbose_name_plural': 'Supermarket-Returns-Damages-Expiry',
            },
        ),
        migrations.CreateModel(
            name='SupermarketSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, default='Supermarket', max_length=500, null=True, verbose_name='Department')),
                ('session', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=500, null=True, verbose_name='Session')),
                ('sales_person', models.CharField(max_length=200, verbose_name='Sales Person')),
                ('category', models.CharField(blank=True, max_length=200, null=True, verbose_name='Category')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('unit_selling_price', models.FloatField(default=0.0, verbose_name='Unit Selling Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
                ('total_selling_price', models.FloatField(default=0.0, verbose_name='Total Selling Price')),
                ('gross_profit', models.FloatField(default=0.0, verbose_name='Gross Profit')),
                ('margin', models.FloatField(default=0.0, verbose_name='margin')),
            ],
            options={
                'verbose_name': 'Supermarket Sales',
                'verbose_name_plural': 'Supermarket Sales',
            },
        ),
    ]
