# Generated by Django 3.2.2 on 2022-04-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermarketsales',
            name='qty',
            field=models.FloatField(default=0.0, verbose_name='Quantity'),
        ),
    ]
