# Generated by Django 3.2.2 on 2022-04-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0003_supermarketreturnsdamages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermarketreturnsdamages',
            name='status',
            field=models.CharField(blank=True, choices=[('Return Inwards', 'Return Inwards'), ('Return Outwards', 'Return Outwards'), ('Damages', 'Damages'), ('Expired', 'Expired')], default='', max_length=200, null=True, verbose_name='Sales Person'),
        ),
    ]
