# Generated by Django 4.0.4 on 2022-04-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0005_supermarketinventory_supermarketproducts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supermarketpurchases',
            name='sales_person',
        ),
        migrations.AddField(
            model_name='supermarketpurchases',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Invoice Id'),
        ),
    ]
