# Generated by Django 3.2.2 on 2022-04-04 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=100, unique=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(max_length=5000)),
                ('instruction1', models.CharField(blank=True, max_length=200, null=True)),
                ('instruction2', models.CharField(blank=True, max_length=200, null=True)),
                ('instruction3', models.CharField(blank=True, max_length=200, null=True)),
                ('instruction4', models.CharField(blank=True, max_length=200, null=True)),
                ('instruction5', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True, max_length=50000, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('state', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='', max_length=300)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Critical', 'Critical')], default='', max_length=300)),
                ('expiry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.employee')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
