# Generated by Django 3.2.2 on 2022-04-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220404_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='task',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='task',
            name='image3',
        ),
    ]
