# Generated by Django 3.2.2 on 2022-04-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20220406_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.CharField(choices=[('Bakery', 'Bakery'), ('Boulangerie', 'Boulangerie'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Ice Cream', 'Ice Cream'), ('Supermarket', 'Supermarket')], default='', max_length=300),
        ),
    ]
