# Generated by Django 3.2.2 on 2022-04-06 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
