# Generated by Django 3.2.2 on 2022-04-06 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, max_length=100, null=True, unique=True),
        ),
    ]
