# Generated by Django 3.2.2 on 2022-03-21 11:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=125, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=125, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Middle Name (optional)')),
                ('id_card_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='ID Card Number')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=255, verbose_name='Gender')),
                ('birthday', models.DateField(default='', verbose_name='Date of Birth (YY/MM/DD)')),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Place of Birth (optional)')),
                ('tribe', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tribe (optional)')),
                ('religion', models.CharField(blank=True, choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Others', 'Others')], default=None, max_length=255, null=True, verbose_name='Religion (optional)')),
                ('nationality', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Nationality (optional)')),
                ('ssnitnumber', models.CharField(blank=True, max_length=30, null=True, verbose_name='Social Insurance Number')),
                ('tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number 1 ')),
                ('tel2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number 2 ')),
                ('email', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Email (optional)')),
                ('current_town', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Hometown (optional)')),
                ('region', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Region (optional)')),
                ('quarter', models.CharField(max_length=125, verbose_name='Current Quarter')),
                ('address', models.TextField(blank=True, help_text='address of current residence', max_length=125, null=True, verbose_name='Address')),
                ('education', models.TextField(blank=True, choices=[('FSLC', 'FSLC'), ('Ordinary Level', 'Ordinary Level'), ('Advanced Level', 'Advanced Level'), ('Bachelor Degree', 'Bachelor Degree'), ('Master Degree', 'Master Degree'), ('MBA', 'MBA'), ('PHD', 'PHD')], max_length=125, null=True, verbose_name='Level of Education')),
                ('lastwork', models.CharField(blank=True, help_text='where was the last place you worked ?', max_length=125, null=True, verbose_name='Last Place of Work')),
                ('previous_employer', models.CharField(blank=True, help_text='Previous Employer ?', max_length=255, null=True, verbose_name='Previous Employer')),
                ('position', models.CharField(blank=True, help_text='what position where you in your last place of work ?', max_length=255, null=True, verbose_name='Position Held')),
                ('location', models.CharField(blank=True, help_text='Location last-work ?', max_length=255, null=True, verbose_name='Location last-work')),
                ('type_of_work', models.CharField(blank=True, help_text='Type of Business?', max_length=255, null=True, verbose_name='Type of Business')),
                ('other_experiences', models.CharField(blank=True, help_text='Other Experiences ?', max_length=255, null=True, verbose_name='Other Experiences')),
                ('reasons_for_termination', models.CharField(blank=True, help_text='Why you left ?', max_length=255, null=True, verbose_name='Reasons for Termination')),
                ('employmenttype', models.CharField(blank=True, choices=[('PART TIME', 'PART TIME'), ('FULL TIME', 'FULL TIME'), ('CONTRACT', 'CONTRACT')], max_length=30, null=True, verbose_name='Employment Type')),
                ('employeeid', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=10, unique=True, verbose_name='Employee ID Number')),
                ('employment_status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('ON LEAVE', 'ON LEAVE'), ('SUSPENDED', 'SUSPENDED'), ('DIMISSED', 'DIMISSED')], max_length=30, null=True, verbose_name='Employement Status')),
                ('startdate', models.DateField(blank=True, help_text='date of employement', null=True, verbose_name='Employement Date')),
                ('enddate', models.DateField(blank=True, help_text='date of employement', null=True, verbose_name='Termination Date')),
                ('total_salary', models.IntegerField(default=0)),
                ('base_salary', models.IntegerField(blank=True, default=0, help_text='Total Salary - sum of all allowance', null=True, verbose_name='Base Salary')),
                ('housing_allowance', models.IntegerField(blank=True, default=0, help_text='15% of Total Salary', null=True, verbose_name='Housing Allowance')),
                ('feeding_allowance', models.IntegerField(blank=True, default=0, help_text='10% of Total Salary', null=True, verbose_name='Feeding Allowance')),
                ('light_allowance', models.IntegerField(blank=True, default=0, help_text='4% of Total Salary', null=True, verbose_name='Electricity Allowance')),
                ('water_allowance', models.IntegerField(blank=True, default=0, help_text='2% of Total Salary', null=True, verbose_name='WaterBill Allowance')),
                ('transport_allowance', models.IntegerField(blank=True, default=0, help_text='10% of Total Salary', null=True, verbose_name='WaterBill Allowance')),
                ('fullname1', models.CharField(help_text='who should we contact ?', max_length=255, null=True, verbose_name='Fullname')),
                ('tel1', models.CharField(default='+237', help_text='Phone Number', max_length=255, verbose_name='Emergency Contact Tel ')),
                ('relationship1', models.CharField(choices=[('FATHER', 'FATHER'), ('MOTHER', 'MOTHER'), ('UNCLE', 'UNCLE'), ('AUNTY', 'AUNTY'), ('BROTHER', 'BROTHER'), ('SISTER', 'SISTER'), ('HUSBAND', 'HUSBAND'), ('WIFE', 'WIFE'), ('BOY FRIEND', 'BOY FRIEND'), ('GIRL FRIEND', 'GIRL FRIEND'), ('OTHERS', 'OTHERS')], help_text='who should we contact ?', max_length=255, null=True, verbose_name='Relationship 1')),
                ('place_of_residence1', models.CharField(max_length=255, null=True, verbose_name='Place of Residence')),
                ('fullname2', models.CharField(help_text='who should we contact ?', max_length=255, null=True, verbose_name='Fullname 2')),
                ('tel3', models.CharField(default='+237', help_text='Phone Number', max_length=255, verbose_name='Emergency Contact Tel ')),
                ('relationship2', models.CharField(choices=[('FATHER', 'FATHER'), ('MOTHER', 'MOTHER'), ('UNCLE', 'UNCLE'), ('AUNTY', 'AUNTY'), ('BROTHER', 'BROTHER'), ('SISTER', 'SISTER'), ('HUSBAND', 'HUSBAND'), ('WIFE', 'WIFE'), ('BOY FRIEND', 'BOY FRIEND'), ('GIRL FRIEND', 'GIRL FRIEND'), ('OTHERS', 'OTHERS')], help_text='who should we contact ?', max_length=255, null=True, verbose_name='Relationship 2')),
                ('place_of_residence2', models.CharField(max_length=255, null=True, verbose_name='Place of Residence')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
            options={
                'verbose_name': 'SubDepartment',
                'verbose_name_plural': 'SubDepartment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Salaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('payment_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Daily', 'Daily')], default='', max_length=100)),
                ('payment_means', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Cheque', 'Cheque'), ('Mobile Money', 'Mobile Money')], default='', max_length=100)),
                ('transaction_id', models.CharField(blank=True, default=uuid.UUID('7fc7d7cc-c7fe-44b6-9705-33f3a8c3e45c'), max_length=500, null=True)),
                ('total_salary', models.IntegerField(default=0)),
                ('base_salary', models.IntegerField(blank=True, default=0, help_text='Total Salary - sum of all allowance', null=True, verbose_name='Base Salary')),
                ('housing_allowance', models.IntegerField(blank=True, default=0, help_text='15% of Total Salary', null=True, verbose_name='Housing Allowance')),
                ('feeding_allowance', models.IntegerField(blank=True, default=0, help_text='10% of Total Salary', null=True, verbose_name='Feeding Allowance')),
                ('light_allowance', models.IntegerField(blank=True, default=0, help_text='4% of Total Salary', null=True, verbose_name='Electricity Allowance')),
                ('water_allowance', models.IntegerField(blank=True, default=0, help_text='2% of Total Salary', null=True, verbose_name='WaterBill Allowance')),
                ('transport_allowance', models.IntegerField(blank=True, default=0, help_text='10% of Total Salary', null=True, verbose_name='WaterBill Allowance')),
                ('overtime', models.IntegerField(blank=True, default=0, null=True)),
                ('commission_and_bonus', models.IntegerField(blank=True, default=0, null=True)),
                ('expenses', models.IntegerField(blank=True, default=0, null=True)),
                ('total_earnings', models.IntegerField(blank=True, default=0, null=True)),
                ('income_tax', models.IntegerField(blank=True, default=0, null=True)),
                ('national_social_insurance', models.IntegerField(blank=True, default=0, null=True)),
                ('other_dedutions', models.IntegerField(blank=True, default=0, null=True)),
                ('reasons_for_deductions', models.TextField(blank=True, max_length=1000, null=True)),
                ('total_deductions', models.IntegerField(blank=True, default=0, null=True)),
                ('total_expected_amount_to_paid', models.IntegerField(blank=True, default=0, null=True)),
                ('total_amount_paid', models.IntegerField(blank=True, default=0, null=True)),
                ('arrears', models.IntegerField(blank=True, default=0, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.employee')),
            ],
            options={
                'verbose_name': 'Salary',
                'verbose_name_plural': 'Salaries',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.subdepartment'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.role'),
        ),
    ]
