# Generated by Django 3.2.2 on 2022-03-21 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('ad00dead-4d88-4216-9a26-b4b4d2eb3e13'), max_length=500, null=True),
        ),
    ]
