# Generated by Django 3.2.2 on 2022-03-23 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('2a6a0322-0334-4b30-b732-6e5764b9506b'), max_length=500, null=True),
        ),
    ]
