# Generated by Django 3.2.2 on 2022-03-27 03:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('2c0a49ae-e2e8-4bdb-9dc0-786e76e34703'), max_length=500, null=True),
        ),
    ]
