# Generated by Django 3.2.2 on 2022-03-27 03:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('e1546744-8c8f-4e68-bb48-16b47fb901d8'), max_length=500, null=True),
        ),
    ]
