# Generated by Django 3.2.2 on 2022-03-27 03:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('852c41b1-16b4-4cab-9a9a-b8e9b3bd9d82'), max_length=500, null=True),
        ),
    ]
