# Generated by Django 3.2.2 on 2022-03-27 06:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('bf63775c-8770-410c-bd4d-19f3345afd76'), max_length=500, null=True),
        ),
    ]
