# Generated by Django 3.2.2 on 2022-03-27 06:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('4a48ad2d-7be4-45a1-83c6-f83ab1c1353b'), max_length=500, null=True),
        ),
    ]
