# Generated by Django 3.2.2 on 2022-03-28 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('26c1960b-0891-4477-9fae-6b4106070767'), max_length=500, null=True),
        ),
    ]
