# Generated by Django 3.2.2 on 2022-03-28 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('ec6bbec8-4e46-4680-9b54-3f5231e67a2d'), max_length=500, null=True),
        ),
    ]
