# Generated by Django 3.2.2 on 2022-03-28 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('1d973241-052c-4540-8cf6-74634b4bd18a'), max_length=500, null=True),
        ),
    ]
