# Generated by Django 3.2.2 on 2022-03-28 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('84bfdd5b-bc08-4d34-bf57-59801b9f534b'), max_length=500, null=True),
        ),
    ]
