# Generated by Django 3.2.2 on 2022-03-28 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('2ceca83e-375e-46d8-81db-a7822a844398'), max_length=500, null=True),
        ),
    ]
