# Generated by Django 3.2.2 on 2022-03-31 05:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('9948ab15-33f9-46bb-a67c-b736237d5a92'), max_length=500, null=True),
        ),
    ]
