# Generated by Django 3.2.2 on 2022-03-31 05:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('05a75ec9-3cbd-443b-bd88-c6ea6878c627'), max_length=500, null=True),
        ),
    ]
