# Generated by Django 3.2.2 on 2022-04-01 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('5155c5c2-0b1c-4dd7-879c-93f42b82242d'), max_length=500, null=True),
        ),
    ]
