# Generated by Django 3.2.2 on 2022-04-04 05:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('a79fa110-50b2-4751-ae46-8973e6634582'), max_length=500, null=True),
        ),
    ]
