# Generated by Django 3.2.2 on 2022-04-04 05:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('736898c6-ec8d-4646-ba53-4aee43e42f8e'), max_length=500, null=True),
        ),
    ]
