# Generated by Django 3.2.2 on 2022-04-04 06:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('57afaf46-07ec-4691-8831-fdc7a90aa5bf'), max_length=500, null=True),
        ),
    ]
