# Generated by Django 3.2.2 on 2022-04-05 13:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('d289e958-e68e-42f2-8ec6-b5d5f33ada83'), max_length=500, null=True),
        ),
    ]
