# Generated by Django 3.2.2 on 2022-04-05 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('93653a4f-a447-4497-9844-f2f4bb7c72b5'), max_length=500, null=True),
        ),
    ]
