# Generated by Django 3.2.2 on 2022-04-06 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('21b84778-3703-49e6-89e8-1b02743f42ab'), max_length=500, null=True),
        ),
    ]
