# Generated by Django 3.2.2 on 2022-04-06 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('dbd7319a-630a-4c24-8da9-cfd605e51baa'), max_length=500, null=True),
        ),
    ]
