# Generated by Django 3.2.2 on 2022-04-06 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0029_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('170149f7-f676-4aca-8e3b-e3ebccc6959d'), max_length=500, null=True),
        ),
    ]
