# Generated by Django 3.2.2 on 2022-04-06 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0030_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('015fb4a1-3168-4918-9756-8b98667484fb'), max_length=500, null=True),
        ),
    ]
