# Generated by Django 3.2.2 on 2022-04-06 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0031_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('319c1397-72f2-42e9-aa6e-f7d6dd9c5e73'), max_length=500, null=True),
        ),
    ]
