# Generated by Django 3.2.2 on 2022-04-07 01:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0032_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('017be1d1-095c-4b22-bd9b-5012e9d2ef7e'), max_length=500, null=True),
        ),
    ]
