# Generated by Django 3.2.2 on 2022-04-07 02:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0034_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('7b33d182-e333-4a53-aaae-32a8fe7c374a'), max_length=500, null=True),
        ),
    ]
