# Generated by Django 3.2.2 on 2022-04-07 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0035_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('864d7141-d7f9-4711-bb89-e82f92df5145'), max_length=500, null=True),
        ),
    ]
