# Generated by Django 3.2.2 on 2022-04-07 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0038_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('6effee84-c3e7-49c3-b7a8-50daa7561fe7'), max_length=500, null=True),
        ),
    ]
