# Generated by Django 3.2.2 on 2022-04-07 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0039_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('f18c408d-653e-4100-9651-80f1168c668f'), max_length=500, null=True),
        ),
    ]
