# Generated by Django 3.2.2 on 2022-04-07 09:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0040_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('6d376ddb-cd26-4a08-b303-d38afc2e95b4'), max_length=500, null=True),
        ),
    ]
