# Generated by Django 3.2.2 on 2022-04-07 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0041_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('092ae93c-06af-458d-8f13-436b899ad4e2'), max_length=500, null=True),
        ),
    ]
