# Generated by Django 3.2.2 on 2022-04-07 09:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0042_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('416db21a-19d0-4e69-9cbe-942f31b1cdf3'), max_length=500, null=True),
        ),
    ]
