# Generated by Django 3.2.2 on 2022-04-07 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0043_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('99c00e24-ec8c-4c43-8cdc-9cdf34403d97'), max_length=500, null=True),
        ),
    ]
