# Generated by Django 3.2.2 on 2022-04-08 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0044_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('a39b8814-b3ff-4aa5-bf7c-bf1a6a46d0e0'), max_length=500, null=True),
        ),
    ]
