# Generated by Django 3.2.2 on 2022-04-08 06:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0047_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('1787783c-ff33-4e86-a5fe-ece86d56eaa3'), max_length=500, null=True),
        ),
    ]
