# Generated by Django 3.2.2 on 2022-04-08 06:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0048_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('b3d427c2-e5ca-4da5-b5ea-fd948a87d231'), max_length=500, null=True),
        ),
    ]
