# Generated by Django 3.2.2 on 2022-04-08 07:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0049_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('318a9714-091f-4d13-9f50-8c34c8e8abca'), max_length=500, null=True),
        ),
    ]
