# Generated by Django 3.2.2 on 2022-04-08 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0050_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('f5454582-88bf-4cd0-9077-5dc906f7febf'), max_length=500, null=True),
        ),
    ]
