# Generated by Django 3.2.2 on 2022-04-08 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0051_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('f3a194f8-373d-4962-b5e8-23f48fbb78d3'), max_length=500, null=True),
        ),
    ]
