# Generated by Django 3.2.2 on 2022-04-08 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0052_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('664ac71c-f7b5-43d3-88d1-a86a62702f40'), max_length=500, null=True),
        ),
    ]
