# Generated by Django 3.2.2 on 2022-04-08 18:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0054_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('720eb92d-167a-499c-a160-91dfe14c084e'), max_length=500, null=True),
        ),
    ]
