# Generated by Django 3.2.2 on 2022-04-08 18:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0055_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('85e147b4-b142-4c36-b7b8-2dcb1bab1ec8'), max_length=500, null=True),
        ),
    ]
