# Generated by Django 3.2.2 on 2022-04-08 20:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0056_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('dd150d6a-6b19-4d24-b9d5-13cdd2f62683'), max_length=500, null=True),
        ),
    ]
