# Generated by Django 3.2.2 on 2022-04-10 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0057_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('cb34e686-d04a-4597-8d13-a6b742ce7dc6'), max_length=500, null=True),
        ),
    ]
