# Generated by Django 3.2.2 on 2022-04-13 06:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0059_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('68e3b8df-66c9-46a2-a75f-38a8624d2942'), max_length=500, null=True),
        ),
    ]
