# Generated by Django 3.2.2 on 2022-04-15 04:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0060_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('b89eeffb-8f69-4e40-ac4a-d23f6180f205'), max_length=500, null=True),
        ),
    ]
