# Generated by Django 3.2.2 on 2022-04-15 04:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0061_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('fed5e050-4065-45a0-b7e4-49b802a05ccb'), max_length=500, null=True),
        ),
    ]
