# Generated by Django 4.0.4 on 2022-04-21 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0064_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('cb35cea5-7148-4200-9dde-ab6a660dcddb'), max_length=500, null=True),
        ),
    ]
