# Generated by Django 4.0.4 on 2022-04-22 03:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0065_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('693164a3-24e5-4425-b270-159d3e339260'), max_length=500, null=True),
        ),
    ]
