# Generated by Django 4.0.4 on 2022-04-22 20:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0067_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('0b006646-1738-48f8-a3e0-2fc5f05869f6'), max_length=500, null=True),
        ),
    ]
