# Generated by Django 4.0.4 on 2022-04-22 20:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0068_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('e154521d-5248-4c28-bc42-b6e1f56f35b7'), max_length=500, null=True),
        ),
    ]
