# Generated by Django 4.0.4 on 2022-04-22 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0069_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('ae5a47f5-c7a4-46b5-92e7-fa89302950e1'), max_length=500, null=True),
        ),
    ]
