# Generated by Django 4.0.4 on 2022-04-22 21:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0070_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('2562b5dd-1795-4ab4-9777-844160f58aca'), max_length=500, null=True),
        ),
    ]
