# Generated by Django 4.0.4 on 2022-04-22 21:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0071_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('fe305344-6213-4277-bbbf-ec0ace77704a'), max_length=500, null=True),
        ),
    ]
