# Generated by Django 4.0.4 on 2022-04-28 07:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0072_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('837c4730-189f-449f-9f16-13b1bf312487'), max_length=500, null=True),
        ),
    ]
