# Generated by Django 4.0.4 on 2022-04-28 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0074_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('b37b3e71-c32c-4b32-891a-0a4e54d39bb5'), max_length=500, null=True),
        ),
    ]
