# Generated by Django 4.0.4 on 2022-05-05 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0077_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('c0a22d30-8149-4ca8-b7d3-ec138686cc4a'), max_length=500, null=True),
        ),
    ]
