# Generated by Django 4.0.4 on 2022-05-06 05:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0078_alter_salaries_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='transaction_id',
            field=models.CharField(blank=True, default=uuid.UUID('8d935a6a-f826-4bca-8b20-63afdddc9249'), max_length=500, null=True),
        ),
    ]
