# Generated by Django 4.0.4 on 2022-07-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=250, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Middle Name (optional)')),
                ('fullname', models.CharField(blank=True, default='', max_length=125, null=True, verbose_name='Full Name (Leave Blank)')),
                ('id_card_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='ID Card Number')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('birthday', models.DateField(default='', verbose_name='Date of Birth (YY/MM/DD)')),
                ('age', models.IntegerField(blank=True, default=0, null=True, verbose_name='Age')),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Place of Birth (optional)')),
                ('tribe', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tribe (optional)')),
                ('religion', models.CharField(blank=True, choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Others', 'Others')], default=None, max_length=255, null=True, verbose_name='Religion (optional)')),
                ('nationality', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Nationality (optional)')),
                ('ssnitnumber', models.CharField(blank=True, max_length=30, null=True, verbose_name='Social Insurance Number')),
                ('tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number 1 ')),
                ('tel2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number 2 ')),
                ('email', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Email (optional)')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
