# Generated by Django 3.2.2 on 2022-03-21 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BakerySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('order_no', models.IntegerField()),
                ('invoice_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Invoice Id')),
                ('supplier', models.CharField(blank=True, choices=[('Moses', 'Moses'), ('Glory', 'Glory'), ('Kesty', 'Kesty')], default='', max_length=500, null=True, verbose_name='Supplier')),
                ('customer', models.CharField(max_length=200, verbose_name='Customer')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('sub_department', models.CharField(blank=True, choices=[('Boulangerie', 'Boulangerie'), ('Patisserie', 'Patisserie')], default='Bakery', max_length=500, null=True, verbose_name='Sub Department')),
                ('category', models.CharField(blank=True, choices=[('Bread', 'Bread'), ('Confectionary', 'Confectionary'), ('Hamburger', 'Hamburger'), ('Sandwich', 'Sandwich'), ('Cake', 'Cake'), ('Milk Bread', 'Milk Bread'), ('Biscuit', 'Biscuit'), ('Croissant', 'Croissant'), ('Fruitage', 'Fruitage')], default='', max_length=500, null=True)),
                ('session', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=500, null=True, verbose_name='Session')),
                ('product', models.CharField(max_length=200, verbose_name='Product Name')),
                ('qty', models.IntegerField(verbose_name='Quantity')),
                ('cost_price', models.FloatField(default=0.0, verbose_name='Cost Price')),
                ('total_amount', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0, verbose_name='Discount')),
                ('discount_value', models.FloatField(default=0.0, verbose_name='Discount Value')),
                ('net_amount', models.FloatField(default=0.0, verbose_name='Net Amount')),
                ('commission', models.FloatField(default=0.0, verbose_name='Commission')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BakerySales',
                'verbose_name_plural': 'BakerySales',
            },
        ),
        migrations.CreateModel(
            name='BakeryRmReturns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('return_manager', models.CharField(max_length=200, verbose_name='Procuement Manager')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('return_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Purchase Invoice Id')),
                ('supplier', models.CharField(max_length=200, verbose_name='Supplier')),
                ('category', models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect')], default='Direct', max_length=500, null=True, verbose_name='Category')),
                ('entry_measure', models.CharField(max_length=200, verbose_name='Entry Measure')),
                ('weight_pack', models.CharField(max_length=200, verbose_name='Weight/Pack')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BakeryRmReturn',
                'verbose_name_plural': 'BakeryRmReturns',
            },
        ),
        migrations.CreateModel(
            name='BakeryRmDamages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('damage_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Purchase Invoice Id')),
                ('category', models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect')], default='Direct', max_length=500, null=True, verbose_name='Category')),
                ('entry_measure', models.CharField(max_length=200, verbose_name='Entry Measure')),
                ('weight_pack', models.CharField(max_length=200, verbose_name='Weight/Pack')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BakeryRmDamage',
                'verbose_name_plural': 'BakeryRmDamages',
            },
        ),
        migrations.CreateModel(
            name='BakeryReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('order_no', models.IntegerField()),
                ('return_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Return Invoice Id')),
                ('invoice_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Invoice Id')),
                ('customer_from', models.CharField(max_length=200, verbose_name='Customer_from')),
                ('customer_to', models.CharField(max_length=200, verbose_name='Customer_to')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('sub_department', models.CharField(blank=True, choices=[('Boulangerie', 'Boulangerie'), ('Patisserie', 'Patisserie')], default='Bakery', max_length=500, null=True, verbose_name='Sub Department')),
                ('category', models.CharField(blank=True, choices=[('Bread', 'Bread'), ('Confectionary', 'Confectionary'), ('Hamburger', 'Hamburger'), ('Sandwich', 'Sandwich'), ('Cake', 'Cake'), ('Milk Bread', 'Milk Bread'), ('Biscuit', 'Biscuit'), ('Croissant', 'Croissant'), ('Fruitage', 'Fruitage')], default='', max_length=500, null=True)),
                ('product', models.CharField(max_length=200, verbose_name='Product Name')),
                ('qty', models.IntegerField(verbose_name='Quantity')),
                ('cost_price', models.FloatField(default=0.0, verbose_name='Cost Price')),
                ('total_amount', models.FloatField(default=0.0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BakeryReturns',
                'verbose_name_plural': 'BakeryReturns',
            },
        ),
        migrations.CreateModel(
            name='BakeryPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('procuement_manager', models.CharField(max_length=200, verbose_name='Procuement Manager')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('purchase_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Purchase Invoice Id')),
                ('supplier', models.CharField(max_length=200, verbose_name='Supplier')),
                ('category', models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect')], default='Direct', max_length=500, null=True, verbose_name='Category')),
                ('entry_measure', models.CharField(max_length=200, verbose_name='Entry Measure')),
                ('weight_pack', models.CharField(max_length=200, verbose_name='Weight/Pack')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BakeryPurchase',
                'verbose_name_plural': 'BakeryPurchases',
            },
        ),
        migrations.CreateModel(
            name='BakeryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('session', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=500, null=True, verbose_name='Session')),
                ('collector', models.CharField(blank=True, choices=[('Moses', 'Moses'), ('Glory', 'Glory'), ('Kesty', 'Kesty'), ('Charles', 'Charles'), ('Cyril', 'Cyril'), ('Aly', 'Aly'), ('Joan', 'Joan'), ('Micheal', 'Micheal'), ('Esther', 'Esther'), ('Violet', 'Violet'), ('Kaba', 'Kaba'), ('Brenda', 'Brenda')], max_length=500, null=True, verbose_name='Collector')),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment Invoice Id')),
                ('customer', models.CharField(max_length=200, verbose_name='Customer')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BakeryPayment',
                'verbose_name_plural': 'BakeryPayments',
            },
        ),
        migrations.CreateModel(
            name='BakeryOpeningBalances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('ob_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='OB No')),
                ('openingbalance_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Opening Balance Id')),
                ('customer', models.CharField(max_length=200, verbose_name='Customer')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BakeryOpeningBalance',
                'verbose_name_plural': 'BakeryOpeningBalances',
            },
        ),
        migrations.CreateModel(
            name='BakeryInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('sub_department', models.CharField(blank=True, choices=[('Boulangerie Morning', 'Boulangerie Morning'), ('Boulangerie Evening', 'Boulangerie Evening'), ('Patisserie', 'Patisserie')], default='', max_length=500, null=True, verbose_name='Sub Department')),
                ('stock_status', models.CharField(blank=True, choices=[('Opening Stock', 'Opening Stock'), ('Closing Stock', 'Closing Stock')], default='', max_length=500, null=True, verbose_name='Stock Status')),
                ('entry_measure', models.FloatField(default=0.0, verbose_name='Entry Measure')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BakeryInventory',
                'verbose_name_plural': 'BakeryInventory',
            },
        ),
    ]
