# Generated by Django 4.0.4 on 2022-06-10 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0002_alter_bakerypayment_collector'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryInventoryMagazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('sub_department', models.CharField(blank=True, choices=[('Boulangerie Morning', 'Boulangerie Morning'), ('Boulangerie Evening', 'Boulangerie Evening'), ('Patisserie Morning', 'Patisserie Morning'), ('Patisserie Evening', 'Patisserie Evening')], default='', max_length=500, null=True, verbose_name='Sub Department')),
                ('stock_status', models.CharField(blank=True, choices=[('Opening Stock', 'Opening Stock'), ('Closing Stock', 'Closing Stock')], default='', max_length=500, null=True, verbose_name='Stock Status')),
                ('direct_indirect', models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect')], default='', max_length=500, null=True, verbose_name='Drect / Indirect')),
                ('entry_measure', models.CharField(blank=True, choices=[('Grams', 'Grams'), ('Kg', 'Kg'), ('Unit', 'Unit'), ('Litre', 'Litre')], default='', max_length=500, null=True, verbose_name='Entry Measure')),
                ('weight_per_pack', models.FloatField(default=0.0, verbose_name='Weight / Pack')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
            ],
            options={
                'verbose_name': 'Bakery Inventory',
                'verbose_name_plural': 'Bakery Inventory',
            },
        ),
        migrations.CreateModel(
            name='BakeryInventorySubDepartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('sub_department', models.CharField(blank=True, choices=[('Boulangerie Morning', 'Boulangerie Morning'), ('Boulangerie Evening', 'Boulangerie Evening'), ('Patisserie Morning', 'Patisserie Morning'), ('Patisserie Evening', 'Patisserie Evening')], default='', max_length=500, null=True, verbose_name='Sub Department')),
                ('stock_status', models.CharField(blank=True, choices=[('Opening Stock', 'Opening Stock'), ('Closing Stock', 'Closing Stock')], default='', max_length=500, null=True, verbose_name='Stock Status')),
                ('direct_indirect', models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect')], default='', max_length=500, null=True, verbose_name='Drect / Indirect')),
                ('entry_measure', models.CharField(blank=True, choices=[('Grams', 'Grams'), ('Kg', 'Kg'), ('Unit', 'Unit'), ('Litre', 'Litre')], default='', max_length=500, null=True, verbose_name='Entry Measure')),
                ('weight_per_pack', models.FloatField(default=0.0, verbose_name='Weight / Pack')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
            ],
            options={
                'verbose_name': 'Bakery Inventory',
                'verbose_name_plural': 'Bakery Inventory',
            },
        ),
        migrations.DeleteModel(
            name='BakeryInventory',
        ),
    ]
