# Generated by Django 3.2.2 on 2022-03-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0002_remove_bakerysales_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakerysales',
            name='qty',
            field=models.FloatField(default=0.0, verbose_name='Quantity'),
        ),
    ]
