# Generated by Django 3.2.2 on 2022-03-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0003_alter_bakerysales_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakerypayment',
            name='employee',
        ),
    ]
