# Generated by Django 4.0.4 on 2022-06-10 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0003_bakeryinventorymagazine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryMagazineDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('procuement_manager', models.CharField(max_length=200, verbose_name='Procuement Manager')),
                ('purchase_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Purchase Invoice Id')),
                ('supplier', models.CharField(max_length=200, verbose_name='Supplier')),
                ('category', models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect')], default='Direct', max_length=500, null=True, verbose_name='Category')),
                ('entry_measure', models.CharField(max_length=200, verbose_name='Entry Measure')),
                ('weight_pack', models.CharField(max_length=200, verbose_name='Weight/Pack')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
            ],
            options={
                'verbose_name': 'Bakery Magazine Distribution',
                'verbose_name_plural': 'Bakery Magazine Distribution',
            },
        ),
        migrations.AlterModelOptions(
            name='bakeryinventorymagazine',
            options={'verbose_name': 'Bakery Inventory Magazine', 'verbose_name_plural': 'Bakery Inventory Magazine'},
        ),
        migrations.AlterModelOptions(
            name='bakeryinventorysubdepartments',
            options={'verbose_name': 'Bakery Inventory Sub-Departments', 'verbose_name_plural': 'Bakery Inventory Sub-Departments'},
        ),
        migrations.AddField(
            model_name='bakerypurchase',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Purchase Invoice Id'),
        ),
        migrations.AlterField(
            model_name='bakerypurchase',
            name='category',
            field=models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect')], default='Magazine', max_length=500, null=True, verbose_name='Location'),
        ),
    ]
