# Generated by Django 3.2.2 on 2022-03-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0004_remove_bakerypayment_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeryreturn',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='bakeryreturn',
            name='order_no',
        ),
        migrations.AlterField(
            model_name='bakeryreturn',
            name='qty',
            field=models.FloatField(verbose_name='Quantity'),
        ),
    ]
