# Generated by Django 3.2.2 on 2022-03-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0005_auto_20220324_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeryopeningbalances',
            name='ob_no',
        ),
    ]
