# Generated by Django 4.0.4 on 2022-06-10 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0005_remove_bakerymagazinedistribution_procuement_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('product', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Product Name')),
                ('category', models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect')], default='Direct', max_length=500, null=True, verbose_name='Category')),
                ('entry_measure', models.CharField(max_length=200, verbose_name='Entry Measure')),
                ('weight_pack', models.CharField(max_length=200, verbose_name='Weight/Pack')),
                ('cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('packaging', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Packaging')),
            ],
            options={
                'verbose_name': 'Products Raw Material',
                'verbose_name_plural': 'Products Raw Materials',
            },
        ),
        migrations.AlterField(
            model_name='bakeryinventorymagazine',
            name='sub_department',
            field=models.CharField(blank=True, choices=[('Boulangerie Morning', 'Boulangerie Morning'), ('Boulangerie Evening', 'Boulangerie Evening'), ('Patisserie Morning', 'Patisserie Morning'), ('Patisserie Evening', 'Patisserie Evening'), ('Magazine', 'Magazine')], default='', max_length=500, null=True, verbose_name='Sub Department'),
        ),
    ]
