# Generated by Django 4.0.4 on 2022-06-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0006_rawmaterials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterials',
            name='created_at',
        ),
    ]
