# Generated by Django 3.2.2 on 2022-03-27 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0006_remove_bakeryopeningbalances_ob_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeryopeningbalances',
            name='employee',
        ),
    ]
