# Generated by Django 4.0.4 on 2022-06-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0007_remove_rawmaterials_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakeryrmreturns',
            options={'verbose_name': 'Raw Material Returns Damages', 'verbose_name_plural': 'Raw Material Returns Damages'},
        ),
        migrations.AddField(
            model_name='bakeryrmreturns',
            name='return_status',
            field=models.CharField(blank=True, choices=[('Return Inwards', 'Return Inwards'), ('Return Outwards', 'Return Outwards'), ('Damages', 'Damages')], default='', max_length=500, null=True, verbose_name='Return Status'),
        ),
    ]
