# Generated by Django 3.2.2 on 2022-03-27 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0007_remove_bakeryopeningbalances_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bakeryopeningbalances',
            old_name='amount',
            new_name='total_amount',
        ),
    ]
