# Generated by Django 3.2.2 on 2022-03-27 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0008_rename_amount_bakeryopeningbalances_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeryinventory',
            name='employee',
        ),
    ]
