# Generated by Django 4.0.4 on 2022-06-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0008_alter_bakeryrmreturns_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakeryrmreturns',
            options={'verbose_name': 'Magazine Raw Material Returns Damages', 'verbose_name_plural': 'Magazine Raw Material Returns Damages'},
        ),
        migrations.AddField(
            model_name='bakerypurchase',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('Return Inwards', 'Return Inwards'), ('Return Outwards', 'Return Outwards'), ('Damages', 'Damages'), ('Purchases', 'Purchases')], default='Purchases', max_length=500, null=True, verbose_name='Stock Status'),
        ),
    ]
