# Generated by Django 3.2.2 on 2022-03-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0009_remove_bakeryinventory_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryinventory',
            name='weight_per_pack',
            field=models.CharField(default='', max_length=500, verbose_name='Weight / Pack'),
        ),
    ]
