# Generated by Django 4.0.4 on 2022-06-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0009_alter_bakeryrmreturns_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakerypurchase',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('Return Inwards', 'Return Inwards'), ('Return Outwards', 'Return Outwards'), ('Damages', 'Damages'), ('Purchases', 'Purchases')], default='', max_length=500, null=True, verbose_name='Stock Status'),
        ),
    ]
