# Generated by Django 3.2.2 on 2022-03-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0011_auto_20220328_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakerypurchase',
            name='employee',
        ),
    ]
