# Generated by Django 4.0.4 on 2022-06-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0011_rename_bakeryrmreturns_bakeryrawmaterialusage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeryinventorysubdepartments',
            name='direct_indirect',
        ),
        migrations.AddField(
            model_name='bakeryinventorysubdepartments',
            name='category',
            field=models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect')], default='', max_length=500, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='bakeryinventorysubdepartments',
            name='rm_total_weight_grams',
            field=models.FloatField(default=0.0, verbose_name='RM Total Weight (Grams)'),
        ),
        migrations.AddField(
            model_name='bakeryinventorysubdepartments',
            name='sub_department_transfers',
            field=models.CharField(blank=True, choices=[('Boulangerie Morning', 'Boulangerie Morning'), ('Boulangerie Evening', 'Boulangerie Evening'), ('Patisserie Morning', 'Patisserie Morning'), ('Patisserie Evening', 'Patisserie Evening'), ('All', 'All')], default='', max_length=500, null=True, verbose_name='Sub Department Transfers'),
        ),
        migrations.AddField(
            model_name='bakeryinventorysubdepartments',
            name='supervisor',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='bakeryinventorysubdepartments',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('Opening Stock', 'Opening Stock'), ('Closing Stock', 'Closing Stock'), ('Returns', 'Returns'), ('Transfer Inwards', 'Transfer Inwards'), ('Transfer Outwards', 'Transfer Outwards'), ('Damages', 'Damages')], default='', max_length=500, null=True, verbose_name='Stock Status'),
        ),
        migrations.AlterField(
            model_name='bakeryinventorysubdepartments',
            name='sub_department',
            field=models.CharField(blank=True, choices=[('Boulangerie Morning', 'Boulangerie Morning'), ('Boulangerie Evening', 'Boulangerie Evening'), ('Patisserie Morning', 'Patisserie Morning'), ('Patisserie Evening', 'Patisserie Evening'), ('All', 'All')], default='', max_length=500, null=True, verbose_name='Sub Department'),
        ),
    ]
