# Generated by Django 4.0.4 on 2022-06-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0013_bakeryrmusagesubdepartments_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BakeryRawMaterialUsage',
        ),
        migrations.AlterField(
            model_name='bakeryrmusagesubdepartments',
            name='mixture_number',
            field=models.CharField(blank=True, choices=[('First Mixture', 'First Mixture'), ('Second Mixture', 'Second Mixture'), ('Third Mixture', 'Third Mixture'), ('Fourth Mixture', 'Fourth Mixture'), ('Fifth Mixture', 'Fifth Mixture'), ('Sixth Mixture', 'Sixth Mixture'), ('Seventh Mixture', 'Seventh Mixture'), ('Eight Mixture', 'Eight Mixture'), ('Ninth Mixture', 'Ninth Mixture'), ('Tenth Mixture', 'Tenth Mixture'), ('Eleventh Mixture', 'Eleventh Mixture'), ('Twelfth Mixture', 'Twelfth Mixture')], default='', max_length=500, null=True, verbose_name='Mixture Number'),
        ),
    ]
