# Generated by Django 4.0.4 on 2022-06-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0014_delete_bakeryrawmaterialusage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakeryinventorysubdepartments',
            options={'verbose_name': 'Bakery Inventory Sub Departments', 'verbose_name_plural': 'Bakery Inventory Sub Departments'},
        ),
        migrations.AlterField(
            model_name='bakeryinventorysubdepartments',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('Opening Stock', 'Opening Stock'), ('Closing Stock', 'Closing Stock'), ('Returns', 'Returns'), ('Transfer Inwards', 'Transfer Inwards'), ('Transfer Outwards', 'Transfer Outwards'), ('Damages', 'Damages'), ('Added Stock', 'Added Stock'), ('Rm Usage', 'Rm Usage')], default='', max_length=500, null=True, verbose_name='Stock Status'),
        ),
        migrations.AlterField(
            model_name='bakeryrmusagesubdepartments',
            name='session',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=500, null=True, verbose_name='Session'),
        ),
    ]
