# Generated by Django 3.2.2 on 2022-03-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0014_bakerypurchase_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakerypurchase',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
