# Generated by Django 3.2.2 on 2022-03-28 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0015_alter_bakerypurchase_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakerypurchase',
            name='slug',
        ),
    ]
