# Generated by Django 3.2.2 on 2022-03-31 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0016_remove_bakerypurchase_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeryrmdamages',
            name='employee',
        ),
    ]
