# Generated by Django 3.2.2 on 2022-03-31 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0017_remove_bakeryrmdamages_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeryrmdamages',
            name='location',
        ),
    ]
