# Generated by Django 3.2.2 on 2022-04-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0018_remove_bakeryrmdamages_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeryrmreturns',
            name='employee',
        ),
    ]
