# Generated by Django 3.2.2 on 2022-04-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0023_auto_20220411_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakerypayment',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Mobile Mponey', 'Mobile Money'), ('Bank', 'Bank'), ('Cheque', 'Cheque')], default='', max_length=200, null=True, verbose_name='Payment Mode'),
        ),
    ]
