# Generated by Django 3.2.2 on 2022-04-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0024_bakerypayment_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakerycustomers',
            name='gps_lat',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='gps_lat'),
        ),
        migrations.AlterField(
            model_name='bakerycustomers',
            name='gps_long',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='gps_long'),
        ),
        migrations.AlterField(
            model_name='bakerycustomers',
            name='phone_1',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='phone_1'),
        ),
        migrations.AlterField(
            model_name='bakerycustomers',
            name='phone_2',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='phone_2'),
        ),
        migrations.AlterField(
            model_name='bakerycustomers',
            name='quarter',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='quarter'),
        ),
        migrations.AlterField(
            model_name='bakerycustomers',
            name='road_street_location',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Road Street Location'),
        ),
        migrations.AlterField(
            model_name='bakerycustomers',
            name='street',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='bakerypayment',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money'), ('Bank', 'Bank'), ('Cheque', 'Cheque')], default='', max_length=200, null=True, verbose_name='Payment Mode'),
        ),
    ]
