# Generated by Django 3.2.2 on 2022-04-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_accounting', '0026_auto_20220415_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cquarter_name')),
            ],
            options={
                'verbose_name': 'Quarter',
                'verbose_name_plural': 'Quarter',
            },
        ),
        migrations.AlterField(
            model_name='bakerycustomers',
            name='busness_type',
            field=models.CharField(blank=True, choices=[('Random Customer', 'Random Customer'), ('Others', 'Others'), ('Company', 'Company'), ('Sole Proprietor', 'Sole Proprietor'), ('Supplier', 'Supplier'), ('Institutions', 'Institutions')], max_length=500, null=True, verbose_name='busness_type'),
        ),
    ]
