# Generated by Django 3.2.2 on 2022-04-08 13:48

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Boulangerie', 'Boulangerie'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Ice Cream', 'Ice Cream')], default='', max_length=500, null=True, verbose_name='Department')),
                ('procurement_manager', models.CharField(blank=True, max_length=500, null=True, verbose_name='Procurement Manager')),
                ('vendor', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('invoice_id', models.CharField(blank=True, max_length=500, null=True)),
                ('stock_dept_invoice_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stock Dept Invoice Id')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Procurement',
                'verbose_name_plural': 'Procurement',
                'ordering': ['-created_at'],
            },
        ),
    ]
