# Generated by Django 3.2.2 on 2022-04-08 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('category', models.CharField(blank=True, choices=[('Company', 'Company'), ('Enterprise', 'Enterprise'), ('Individual', 'Individual'), ('School', 'School'), ('NGOs', 'NGOs')], max_length=10, null=True, verbose_name='Category')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Company Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('address', models.TextField(max_length=255, null=True, verbose_name='Address')),
                ('city', models.CharField(default='Kumba', max_length=100, verbose_name='City')),
                ('region', models.CharField(default='South West Region', max_length=200, verbose_name='Region')),
                ('phone', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +237', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('bank_account_no_1', models.CharField(default='Kumba', max_length=100, verbose_name='Bank Account No 1')),
                ('bank_name_1', models.CharField(default='Kumba', max_length=100, verbose_name='Bank Name 1')),
                ('location_1', models.CharField(default='Kumba', max_length=100, verbose_name='Location 1')),
                ('bank_account_no_2', models.CharField(default='Kumba', max_length=100, verbose_name='Bank Account No 2')),
                ('bank_name_2', models.CharField(default='Kumba', max_length=100, verbose_name='Bank Name 2')),
                ('location_2', models.CharField(default='Kumba', max_length=100, verbose_name='Location 2')),
                ('mobile_money_account_1', models.CharField(default='Kumba', max_length=100, verbose_name='Mobile Money Account 1')),
                ('mobile_money_account_2', models.CharField(default='Kumba', max_length=100, verbose_name='Mobile Money Account 2')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
