# Generated by Django 3.2.2 on 2022-04-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Enterprise', 'Enterprise'), ('Individual', 'Individual'), ('School', 'School'), ('NGOs', 'NGOs')], default='', max_length=200, null=True, verbose_name='Company Type'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Supplier', 'Supplier'), ('Bank', 'Bank'), ('Technician', 'Technician')], max_length=10, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Contact Name'),
        ),
    ]
