# Generated by Django 3.2.2 on 2022-04-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_list', '0004_auto_20220408_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='quarter',
            field=models.CharField(default='', max_length=100, verbose_name='Quarter'),
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(default='', max_length=100, verbose_name='street'),
        ),
    ]
