# Generated by Django 3.2.2 on 2022-04-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_list', '0005_auto_20220408_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='quarter',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Quarter'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='street',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='street'),
        ),
    ]
