# Generated by Django 3.2.2 on 2022-04-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_list', '0006_auto_20220408_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='location_1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='location_2',
        ),
        migrations.AddField(
            model_name='contact',
            name='bank_accnt_name_1',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Bank Account Name 1'),
        ),
        migrations.AddField(
            model_name='contact',
            name='bank_accnt_name_2',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Bank Account Name 2'),
        ),
        migrations.AddField(
            model_name='contact',
            name='tax_payer_no',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Tax Payers No'),
        ),
    ]
